version: '3.7'

services:
    composer:
        image: composer
        command: composer
        working_dir: /app
        volumes:
            - .:/app
            - ./vendor:/app/vendor:delegated
            - ./var:/app/var:delegated
