version: '3.7'

volumes:
    mysql-data:
        driver: local

services:
    web:
        working_dir: /var/task
        image: bref/fpm-dev-gateway
        ports:
        - 8000:80
        volumes:
        - .:/var/task
        depends_on:
        - php
        - database
        env_file:
          - .env
        environment:
            HANDLER: public/index.php
            DOCUMENT_ROOT: public
            
    php:
        working_dir: /var/task
        image: bref/php-74-fpm-dev
        volumes:
        - .:/var/task

    database:
        image: mysql:5.7
        ports:
        - 3306:3306
        volumes:
        - mysql-data:/var/lib/mysql
        environment:
            MYSQL_USER: kdti
            MYSQL_PASSWORD: kdti
            MYSQL_DATABASE: kdti
            MYSQL_ROOT_PASSWORD: root

    blackfire:
        image: blackfire/blackfire
        environment:
            BLACKFIRE_SERVER_ID: server-id
            BLACKFIRE_SERVER_TOKEN: server-token
