version: 2.1

orbs:
    codecov: codecov/codecov@1.0.2
    aws-s3: circleci/aws-s3@1.0.11

jobs:
    build:
        docker:
            - image: circleci/php:7.3-cli
              environment:
                APP_ENV: test
                DATABASE_URL: mysql://kdti:kdti@127.0.0.1:3306/kdti?serverVersion=5.7
            - image: circleci/mysql:5.7
              environment:
                MYSQL_USER: kdti
                MYSQL_PASSWORD: kdti
                MYSQL_DATABASE: kdti
                MYSQL_ROOT_PASSWORD: root
        steps:
            - checkout
            - run: php -m
            - run: sudo docker-php-ext-install -j$(nproc) pdo_mysql
            - run: sudo composer self-update
            - run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader
            - run: bin/console doctrine:migrations:migrate --no-interaction
            - run: sudo rm -rf /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - run: sudo echo -e "memory_limit = 2G" | sudo tee /usr/local/etc/php/php.ini > /dev/null
            - run: phpdbg -qrr bin/phpunit --coverage-clover coverage.xml
            - codecov/upload:
                file: coverage.xml
    deploy:
        docker:
            - image: circleci/php:7.3-cli
              environment:
                APP_ENV: prod
        steps:
            - checkout
            - run: php -m
            - run: sudo composer self-update
            - run:
                name: "Composer install"
                command: composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader --no-dev
            - run:
                name: "Cache warmup"
                command: bin/console cache:warmup --env=prod
            - run:
                name: "Update Node.js and npm"
                command: |
                  curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
                  curl https://www.npmjs.com/install.sh | sudo bash
            - run:
                name: "Install serverless"
                command: sudo npm i -g serverless
            - run:
                name: "Serverless deploy"
                command: serverless deploy --stage prod
            - run:
                name: "Run migrations"
                command: vendor/bin/bref cli kdti-backend-prod-console -- doctrine:migrations:migrate --env=prod
            - aws-s3/sync:
                from: 'public/bundles'
                to: 's3://kdti-statics/bundles'
                arguments: |
                  --acl public-read \
                  --cache-control "max-age=86400" \
                  --delete
                overwrite: true
    deploy-staging:
        docker:
            - image: circleci/php:7.3-cli
              environment:
                APP_ENV: staging
        steps:
            - checkout
            - run: php -m
            - run: sudo composer self-update
            - run:
                name: "Composer install"
                command: composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader --no-dev
            - run:
                name: "Cache warmup"
                command: bin/console cache:warmup --env=staging
            - run:
                name: "Update Node.js and npm"
                command: |
                  curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
                  curl https://www.npmjs.com/install.sh | sudo bash
            - run:
                name: "Install serverless"
                command: sudo npm i -g serverless
            - run:
                name: "Serverless deploy"
                command: serverless deploy --stage staging
            - run:
                name: "Run migrations"
                command: vendor/bin/bref cli kdti-backend-staging-console -- doctrine:migrations:migrate --env=staging
            - aws-s3/sync:
                from: 'public/bundles'
                to: 's3://kdti-statics-staging/bundles'
                arguments: |
                  --acl public-read \
                  --cache-control "max-age=86400" \
                  --delete
                overwrite: true

workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: staging
